version: "3"

services:
  db:
    image: 'postgres:14.5'
    restart: always
    ports:
      - '54329:5432'
    environment:
      POSTGRES_DB: typing
      POSTGRES_USER: typing
      POSTGRES_PASSWORD: password
  server:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - ./server:/app
    environment:
      - PORT=8080
    ports:
      - 8080:8080
  frontend:
    depends_on:
      - db
      - server
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/home/node/app
    