version: "3.9"

services:
  db:
    image: "postgres:14.5"
    restart: always
    ports:
      - "54329:5432"
    environment:
      POSTGRES_DB: typing
      POSTGRES_USER: typing
      POSTGRES_PASSWORD: password
  
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
      
  server_dev:
    profiles:
      - dev
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
      context: ./server
      target: dependencies
    volumes:
      - ./server:/app
    environment:
      - PORT=8080
    ports:
      - 8080:8080
    command: /bin/bash -c
      "make clean
      && make seed
      && make develop"

  frontend_dev:
    profiles:
      - dev
    depends_on:
      - db
      - server_dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dependencies
    environment:
      - PORT=3000
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api
      - BACKEND_HOST=server_dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/home/node/app
    command: yarn dev

  server_build:
    profiles:
      - build
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
      context: ./server
    environment:
      - PORT=8080
    ports:
      - 8080:8080
    command: ./tmp/main

  frontend_build:
    profiles:
      - build
    depends_on:
      - db
      - server_build
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BACKEND_HOST=server_build
    environment:
      - PORT=3000
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api
    ports:
      - 3000:3000
